---
apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: syn.tools/v1
kind: PostgreSQLInstance
metadata:
  name: postgres1
  namespace: my-app
spec:
  parameters:
    resources:
      storageSize: 10Gi
      limits:
        memory: 1Gi
    updatePolicy:
      version: '13.7'
      securityUpdates: '*/10 * * * *'
