apiVersion: batch/v1
kind: Job
metadata:
  name: connection-tests
  namespace: my-app
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pgsql
          image: docker.io/bitnami/postgresql:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: test
          securityContext:
            runAsUser: 0
          command:
            - /bin/sh
            - -c
          args:
            - PGDATABASE="postgres" PGUSER="$username" PGPASSWORD="$password" psql --host="$endpoint" -c "select 1";
