name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  KIND_CMD: kind # kind is pre-installed in GitHub runners

jobs:
  crossplane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install krew
        run: |
          wget https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-linux_amd64.tar.gz &&\
          tar zxvf krew-linux_amd64.tar.gz &&\
          ./krew-linux_amd64 install krew

      - name: Install kuttl
        run: PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" kubectl krew install kuttl

      - name: Run tests
        run: PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" make tests

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run docs-html
        run: make docs-html
